### ISSUE TITLE
Set up Custom Font

### ISSUE THREAD

**Issue by camball** [camball/camball.io#3]
Found three fonts on [fontshare.com](https://www.fontshare.com/) that are nice:

- [~~Sentient~~](https://www.fontshare.com/fonts/sentient) Crimson Pro is better for my site, plus it's open source.
- [~~Erode~~](https://www.fontshare.com/fonts/erode) Similar to Sentient, but Sentient is better.
- [Crimson Pro](https://www.fontshare.com/fonts/crimson-pro) ✅

Going with Crimson Pro for now. Later I found out about [Google Fonts](https://fonts.google.com), and [found Crimson Pro on there](https://fonts.google.com/specimen/Crimson+Pro?selection.family=Crimson+Pro).

From the embed generator there, it produced the following to add to the document `head`:

```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
```

All the tutorials out there for adding a custom font with Tailwind are for v3 and not v4, so they all say to extend the font family in `tailwind.config.js`. As Tailwind 4 currently doesn't support that file (they will for back compat, just not yet), we will need to use the new CSS-native-feeling way. Their example looks like the following

```css
@import "tailwindcss";

@theme {
  --font-family-display: "Satoshi", "sans-serif";

  --breakpoint-3xl: 1920px;

  --color-neon-pink: oklch(71.7% 0.25 360);
  --color-neon-lime: oklch(91.5% 0.258 129);
  --color-neon-cyan: oklch(91.3% 0.139 195.8);
}
```

, so let's see if we can get it working.
